# 1. Cổng mặc định của Eureka
server.port=8761

# 2. Tên của ứng dụng
spring.application.name=discovery-server

# 3. Quan trọng: Không cho phép Eureka Server tự đăng ký chính nó
eureka.client.register-with-eureka=false

# 4. Quan trọng: Không cần lấy danh sách các service khác từ server khác
eureka.client.fetch-registry=false
# 5. Cấu hình đường dẫn cho bảng điều khiển (Dashboard)
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/