# Xóa dòng uri cũ, dùng 3 dòng này:
spring.mongodb.uri=mongodb://localhost:27017/product_db
# Giữ các cấu hình khác
server.port=8087
spring.application.name=product-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Bật log này để thấy tận mắt database được chọn lúc SAVE dữ liệu
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG