spring.mongodb.uri=mongodb://mongo:27017/product_db
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.instance.hostname=product-service
management.endpoints.web.exposure.include=health
